language: node_js
node_js:
- '0.10'
services: mongodb
before_install:
- npm install -g grunt-cli
install:
- npm install
before_script:
env:
  global:
    secure: p5XfPMMLOvlfk1BONxvtXdAaWft/HLWkO4rzrRWr+YQkDCDj9rcy50gyZxtKlAzWhPlWTS8fA5Kg+qOdW4JNTF5Dj0yvT03bC9fDfZycwjU7SBzn+c0iGSCvSO7i8kXeGJ/htgc9oBQOcBWpSg5rZDQqwvSfmxKDl0W19WD8bBw=
notifications:
  irc:
    channels:
    - 'chat.freenode.net#spacelab'
